export const __API__URL = "https://localhost:64567/api"
export const __API_LOGIN = __API__URL + "/Auth/Login"
export const __API_FIND_USER_DNI = __API__URL + "/User/Dni/"
export const __API_FIND_USER_EMAIL = __API__URL + "/User/Email/"
export const __API_USER = __API__URL + "/User/"
export const __API_SUBJECT = __API__URL + "/Subject/"
export const __API_INSCWINDOW = __API__URL + "/InscriptionWindow/"
