export const __API__URL = "https://localhost:44355/api"
export const __API_LOGIN = __API__URL + "/Auth/Login"
export const __API_FIND_USER_DNI = __API__URL + "/User/Dni/"
export const __API_FIND_USER_EMAIL = __API__URL + "/User/Email/"
export const __API_USER = __API__URL + "/User/"
