version: "3"
services:
    db:
        image:  "mcr.microsoft.com/mssql/server"
        container_name: db
        environment:
            SA_PASSWORD: "Unla2020"
            ACCEPT_EULA: "Y"
    ddsdguarani_web:
        build: .
        depends_on:
            - db
        ports:
            - 8090:8090

        